### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by zixiiu** [fengjueming/unblock-NetEaseMusic#1]
你好，
非常感谢服务器的搭建，以下是一些基于个人的测试：

iOS 网易云音乐 4.0.1， 设备 iPhone 6

Wifi环境 使用iOS pac文件 导致网易云音乐闪退

wifi/LTE 使用 shadowrocket.conf 会导致网易云音乐无可用网络
（第一次用shadowrocket，可能是我的配置问题）

服务器能ping通，通过越狱修改hosts的方法可以正确解除地区限制

希望能帮助到你

**Comment by fengjueming** [comment]
Hi

感谢反馈，
闪退问题是我放pac的nginx重启之后忘了开了。。。

shadowrocket之前更新后有BUG导致无法使用，昨天更新的新版就没有问题了。

以上。
