### ISSUE TITLE
iOS 客户端需要额外的 hosts 列表

### ISSUE THREAD

**Issue by evansan** [fengjueming/unblock-NetEaseMusic#10]
158.199.142.239 music.163.com
158.199.142.239 p1.music.126.net
158.199.142.239 p2.music.126.net
158.199.142.239 p3.music.126.net
158.199.142.239 p4.music.126.net

158.199.142.239 ip.ws.126.net
158.199.142.239 nstool.netease.com
158.199.142.239 mam.netease.com

0.0.0.0 music.httpdns.c.163.com

加了后面几个地址后就可以播放了

**Comment by idomori** [comment]
好像不好使了

**Comment by evansan** [comment]
好像是代理失效了

**Comment by fengjueming** [comment]
我看看过几天能不能提供个专用SS给大家用

**Comment by fengjueming** [comment]
找到一个临时解决方案了，需要Surge或者其他类似软件的配合。
[Proxy]
CloudMusic= http, 158.199.142.239, 80,,
[Rule]
USER-AGENT,NeteaseMusic*,CloudMusic

建议加上图片缓存，这样效率更高

**Comment by HenryQW** [comment]
> 找到一个临时解决方案了，需要Surge或者其他类似软件的配合。
> [Proxy]
> CloudMusic= http, 158.199.142.239, 80,,
> [Rule]
> USER-AGENT,NeteaseMusic*,CloudMusic
> 
> 建议加上图片缓存，这样效率更高

地区英国

~昨天开始已经失效了，无法登陆，游客登录无法播放任何歌曲。~

改了下配置又可以了，移除了所有的[Host]就可以了= = 很不解

Surge 配置：
```
[General]
loglevel = notify
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 127.0.0.1, localhost, *.local

[Replica]
hide-apple-request = true
hide-crashlytics-request = true
hide-udp = true
use-keyword-filter = false

[Proxy]
网易云音乐 = http, 158.199.142.239, 80, , 

[Proxy Group]
选择代理服务器 = select, 网易云音乐

[Rule]
USER-AGENT,NeteaseMusic*,网易云音乐
FINAL,DIRECT

[URL Rewrite]
^http(|s)?://.*?/eapi/ http://music.163.com/eapi/ header
```
