### ISSUE TITLE
改了hosts之后网页版无法访问？

### ISSUE THREAD

**Issue by tautomer** [fengjueming/unblock-NetEaseMusic#13]
![image](https://user-images.githubusercontent.com/15900605/43277151-20cd35a0-90d5-11e8-8af8-6efbc66296fb.png)
但是客户端没问题
![image](https://user-images.githubusercontent.com/15900605/43277164-30243f26-90d5-11e8-9829-c4e85e38a102.png)

**Comment by Aqua-Dream** [comment]
一样的问题

**Comment by steven7851** [comment]
网页版现在强制使用 https，浏览器可使用插件修改 headers，X-Real-IP 设值为国内IP即可
`X-Real-IP 111.47.226.198`
`http*://*music.163.com/*`
`183.240.52.150 m10.music.126.net`
`https://m10.music.126.net/*`
`http://m10.music.126.net/$1`

https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj
![snipaste_20180728_134709](https://user-images.githubusercontent.com/6252238/43353485-c1c01ab6-926c-11e8-8059-cb7d60389bf0.png)

**Comment by hannesgao** [comment]
@steven7851 好插件，收藏了
另外修改header对强制https和需要跳转到https链接的URL无效，依旧会出现上述问题

**Comment by steven7851** [comment]
改header就不用修改hosts了，或者用这个官方IP `223.252.199.66 music.163.com`
客户端unblock推荐使用https://github.com/nondanee/UnblockNeteaseMusic

**Comment by fengjueming** [comment]
如果是Mac的话建议直接使用客户端。
