### ISSUE TITLE
代理不可用

### ISSUE THREAD

**Issue by zhilinh** [fengjueming/unblock-NetEaseMusic#14]
尝试在Windows中添加代理和在网易云音乐客户端上使用代理均显示代理不可用，坐标美国。谢谢！

**Comment by hannesgao** [comment]
windows直接改hosts

**Comment by zhilinh** [comment]
Win10下使用echo命令修改hosts，可能会把地址加在系统已有的`192.168.56.1 windows10.microdone.cn`后，使得hosts失效。最好是手动添加，然后就可以听了，虽然图片加载不了。感谢分享！

**Comment by retaker** [comment]
把pic那几个去掉之后就能加载图片了，图片不需要走hosts

**Comment by zhilinh** [comment]
@retaker 可以了，谢谢！
