### ISSUE TITLE
8月份开始连接有明显的卡顿，客户端的音乐部分加载不了，大部分是国语歌，怀疑是不是netease那边把音乐分服务器存放了

### ISSUE THREAD

**Issue by haroldvandy2013** [fengjueming/unblock-NetEaseMusic#15]

**Comment by haroldvandy2013** [comment]
另外能不能分享一下搭建服务器的大概思路，我在尝试自己也搭建一个

**Comment by hannesgao** [comment]
我猜，大概是个基于Caddy的HTTPS反向代理？

**Comment by kevin335200** [comment]
这个代理没有处理音乐服务器的部分，就是m开头的地址，比如m8.music.126.cn，所以速度和直连是一样的。。
你需要找你那里比较快的cdn地址来替换
参考
https://github.com/acgotaku/NetEaseMusicWorld
现在还有m8c,m7c这样的名字
贴个Mac下我的防火墙截图，因为不听华语歌，可能有更多服务器。
![screen shot 2018-08-19 at 11 06 05 pm](https://user-images.githubusercontent.com/15524267/44313265-a3851600-a405-11e8-8aed-fe534bd3ada7.png)

**Comment by fengjueming** [comment]
> 这个代理没有处理音乐服务器的部分，就是m开头的地址，比如m8.music.126.cn，所以速度和直连是一样的。。
> 你需要找你那里比较快的cdn地址来替换
> 参考
> https://github.com/acgotaku/NetEaseMusicWorld
> 现在还有m8c,m7c这样的名字
> 贴个Mac下我的防火墙截图，因为不听华语歌，可能有更多服务器。
> ![screen shot 2018-08-19 at 11 06 05 pm](https://user-images.githubusercontent.com/15524267/44313265-a3851600-a405-11e8-8aed-fe534bd3ada7.png)

音乐服务器其实有CDN，但网易这个真的很迷。。。

**Comment by fengjueming** [comment]
> 我猜，大概是个基于Caddy的HTTPS反向代理？

基于HTTPS会涉及到证书问题。目前的解决方案是应用全局通过Proxy，这样会因为没有HTTPS而主动回落HTTP。
服务器是使用Nginx实现的。
