### ISSUE TITLE
Shadowrocket配置

### ISSUE THREAD

**Issue by tensorcopy** [fengjueming/unblock-NetEaseMusic#18]
我用shadowrocket设置了个代理，但是仍然无法加载出歌单。能否给一些指导如何配置？谢谢🙏

**Comment by tensorcopy** [comment]
我只能选用Proxy模式连接加载出歌单，但是别的应用的网就断了。换成config歌单又灰了

**Comment by fengjueming** [comment]
USER-AGENT,NeteaseMusic*
以这样的状态将所有云音乐的流量经由HTTP服务器即可。
如果你有Surge/Quantumult等客户端，则可以单独指定服务器
