### ISSUE TITLE
失效

### ISSUE THREAD

**Issue by Raymond0212** [fengjueming/unblock-NetEaseMusic#19]
服务器配置好像失效了，最近几天刚出现的问题。

**Comment by wayneking04** [comment]
same here

**Comment by Raymond0212** [comment]
Connection is available now.

**Comment by ryoki805** [comment]
windows / ios 均可用

**Comment by Raymond0212** [comment]
最近网易云好像国外不要翻墙了

**Comment by yinketao** [comment]
还是要的啊

发送自 Windows 10 版邮件应用

发件人: Raymond0212
发送时间: 2018年10月15日 4:52
收件人: fengjueming/unblock-NetEaseMusic
抄送: Subscribed
主题: Re: [fengjueming/unblock-NetEaseMusic] 失效 (#19)

最近网易云好像国外不要翻墙了

**Comment by ryoki805** [comment]
不知道该怎么检测，但是电暖端配置前和配置后歌单列表是不一样的。手机端没有比较，但是目前和电脑的歌单一致。应该是这个代理设置的功劳。

**Comment by hannesgao** [comment]
坐标南德，Mac/Win10测试可用，服务器可以ping通，没有失效。

**Comment by koko0v0** [comment]
地点北美， Win10测试已失效

15分钟后状态更新:

可能是NetEase服务器问题:
![image](https://user-images.githubusercontent.com/24643433/47059354-a5adeb80-d18e-11e8-8e84-4c97aab4a2fe.png)

**Comment by mwftts** [comment]
> 最近网易云好像国外不要翻墙了

哈哈， 你这玩笑不好玩。。

**Comment by Hoshino-Mirai** [comment]
北美，Win 10，直接`echo 158.199.142.239 music.163.com p1.music.126.net p2.music.126.net p3.music.126.net p4.music.126.net >> C:\WINDOWS\System32\drivers\etc\hosts`无效，用Notepad打开hosts文件手动加入换行，有效。

**Comment by billgoo** [comment]
> 北美，Win 10，直接`echo 158.199.142.239 music.163.com p1.music.126.net p2.music.126.net p3.music.126.net p4.music.126.net >> C:\WINDOWS\System32\drivers\etc\hosts`无效，用Notepad打开hosts文件手动加入换行，有效。

北美，刚刚试了一下这个方法然而并没有用

**Comment by snznedta** [comment]
北美,macOS, 失效了

**Comment by yinketao** [comment]
北美 win10，失效，哭哭哭

发送自 Windows 10 版邮件应用

发件人: Xin Sun
发送时间: 2018年10月31日 14:25
收件人: fengjueming/unblock-NetEaseMusic
抄送: yinketao; Comment
主题: Re: [fengjueming/unblock-NetEaseMusic] 失效 (#19)

北美,macOS, 失效了

**Comment by zizzen** [comment]
北美 win10 失效~

**Comment by fengjueming** [comment]
fixed
