### ISSUE TITLE
服务器连不上了？

### ISSUE THREAD

**Issue by cheng-01037** [fengjueming/unblock-NetEaseMusic#2]
坐标美帝 6月24日，好人一生平安

**Comment by fengjueming** [comment]
国内节点挂了没注意，已经修复。

**Comment by MikeChongCan** [comment]
您好，现在还能用吗？158.199.142.239 似乎不在线了

**Comment by fengjueming** [comment]
Hi,
服务器没挂，主要是网易云音乐部分客户端开始强制https，https的转发没有证书不太好实现，可以选择使用Mac
客户端下载之后拷贝到手机，或者干掉网易云音乐的https链接。

**Comment by MikeChongCan** [comment]
感谢，我主要就是 Mac 需求！
赞美 repo 主~

**Comment by karlcheong** [comment]
@fengjueming 
https 部分可以使用 [sniproxy](https://github.com/dlundquist/sniproxy) 轉發

**Comment by fengjueming** [comment]
@karlcheong 
感谢推荐，不过这个无法与现有环境兼容，我之后还是考虑提供个证书好了。
