### ISSUE TITLE
失效

### ISSUE THREAD

**Issue by dz0039** [fengjueming/unblock-NetEaseMusic#20]
心痛

**Comment by miracle0930** [comment]
同发现失效，心痛

**Comment by Trigon** [comment]
心痛QAQ

**Comment by sycmio** [comment]
同失效，sad

**Comment by HeavenlyChorus** [comment]
同失效

**Comment by kennethtl0522** [comment]
同失效

**Comment by Nehalem-Lf** [comment]
同失效

**Comment by sanmeiji** [comment]
失效+1

**Comment by shichao-ma** [comment]
失效+2

**Comment by sytang7** [comment]
失效，复读机

**Comment by Alalakii** [comment]
我的下一句是，失效

**Comment by jackiejtr** [comment]
你们有点皮啊 mute了

**Comment by hannesgao** [comment]
这么多人说失效，就没个人来搞个相同的反代吗？同mute了，自己搭一个去。

**Comment by Zcalory** [comment]
失效TOT

**Comment by unheroooo** [comment]
失效+1

**Comment by Aqua-Dream** [comment]
> 这么多人说失效，就没个人来搞个相同的反代吗？同mute了，自己搭一个去。

怎么搭，有服务器，没教程= =

**Comment by Nehalem-Lf** [comment]
> > 这么多人说失效，就没个人来搞个相同的反代吗？同mute了，自己搭一个去。
> 
> 怎么搭，有服务器，没教程= =

https://jixun.moe/post/ymusic-hosts-fix/

**Comment by ChicagoJ** [comment]
心痛T^T

**Comment by jackalsin** [comment]
> > > 这么多人说失效，就没个人来搞个相同的反代吗？同mute了，自己搭一个去。
> > 
> > 
> > 怎么搭，有服务器，没教程= =
> 
> https://jixun.moe/post/ymusic-hosts-fix/

我不知道是不是你写的：

1.  `firewall-cmd` 不需要 `reload`
1. 话说你们直接装`epel`就能直接用`epel`了？我怎么一直都不能用镜像 。。。用的是baseurl

**Comment by fengjueming** [comment]
fixed
