### ISSUE TITLE
请问一下如何撤销cmd的那条命令...目前进入网易云的主页会跳转到这个网址

### ISSUE THREAD

**Issue by geyestella** [fengjueming/unblock-NetEaseMusic#26]
![image](https://user-images.githubusercontent.com/43089824/51364679-db5cca80-1b17-11e9-9067-4d66bbbeb9e7.png)

**Comment by geyestella** [comment]
修改host文件解决了

**Comment by IanB64** [comment]
@geyestella 请问下 windows系统下 怎么撤销的那条指令？谢谢

**Comment by geyestella** [comment]
@IanB64 进入C:\WINDOWS\System32\drivers\etc\hosts然后把相关的指令删掉就可以了
