### ISSUE TITLE
Windows下无法使用，Linux下可以（含部分调试结果）

### ISSUE THREAD

**Issue by mason1900** [fengjueming/unblock-NetEaseMusic#28]
凡没有缓存过的歌曲在Windows下都加载失败（版本2.5.2），而在Linux下可用。
Windows 10下设置好hosts后用fiddler**可以看到有HTTPS Response** ，但是网易云音乐显示加载失败，访问的地址也主要是您hosts里的地址——也就是说服务器本身没有挂，并且hosts劫持的地址是正确的，但不确定在哪个环节出了问题。
注：这里提一点，在验证此问题时需要注意：当去掉hosts条目采用其它国内代理方式以后，网易云音乐可以缓存**地理位置**约一天左右（暂时不确定是服务器端还是本地缓存），无论是缓存过的歌曲还是未缓存过的都可以听，之后缓存过期就显示当前地区不可用，再次需要代理.

**Comment by 54iceblock** [comment]
如果你是用命令添加的hosts的话，可以尝试手动添加看看。命令添加的话可能不会自动换行

**Comment by thanksshu** [comment]
使用手动添加入host后访问：提示证书不安全，添加信任后，依旧显示连接不安全，- Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0.1
猜想原因多半是火狐的安全策略，遂更换IE11测试，成功登录、解锁歌曲，却依旧不能播放。

**Comment by thanksshu** [comment]
手动添加到Host，并更换为Win10下UWP应用后即可使用；
未测试PC客户端能否使用，因为个人暂时无法解决PC客户端下载问题。

**Comment by mason1900** [comment]
> 如果你是用命令添加的hosts的话，可以尝试手动添加看看。命令添加的话可能不会自动换行

我是用Notepad++ 手动操作的。**服务器本身没有挂**，***hosts劫持的地址是正确的***，***可以看到有HTTPS Response***，**hosts劫持成功**，但是Windows下PC版加载失败，只能删hosts开代理。UWP版暂未测试，不过UWP版不支持最新的心动模式。

**Comment by thanksshu** [comment]
随便找了一个版本的PC端，加载成功并能够使用，不知道您为何不成功，我可能无法提供帮助了……

**Comment by thanksshu** [comment]
发现了有意思的现象，不清楚是否普遍——在登陆UWP客户端之后，手机、PC端便可以登录解锁，实属奇特。

**Comment by JigaoLuo** [comment]
Linux Ubuntu18.04 LTS还可以用吗

**Comment by wangyongjie-ntu** [comment]
> Linux Ubuntu18.04 LTS还可以用吗

我这边不可以，没有网络连接

**Comment by thanksshu** [comment]
有另外的项目可以做替代：https://github.com/nondanee/UnblockNeteaseMusic

**Comment by mason1900** [comment]
问题似乎自动解决了， 原因不明
使用了以下的hosts
```
158.199.142.239 music.163.com
158.199.142.239 interface.music.163.com
```
