### ISSUE TITLE
Mac在修改host之后访问网易云会跳转到你的博客？？？

### ISSUE THREAD

**Issue by Carminiumn** [fengjueming/unblock-NetEaseMusic#29]
<img width="1211" alt="2019-02-06 5 12 11" src="https://user-images.githubusercontent.com/44073079/52384680-5e948080-2a33-11e9-8a03-e6f2deb5e783.png">

**Comment by zjwbupt** [comment]
应该是都跳转到楼主的ip地址上去了，不知道这样有没有安全隐患

**Comment by fengjueming** [comment]
好吧其实是我的nginx配置文件没写默认情况下的处理，所以优先跳到我的blog去了，已经修复这个问题。
