### ISSUE TITLE
iphone好像不行？

### ISSUE THREAD

**Issue by Aries0331** [fengjueming/unblock-NetEaseMusic#3]
改了proxy还是用不了

**Comment by fengjueming** [comment]
iPhone客户端现在处理方式比较多，没办法直接用pac实现。
现在App会向服务器直接请求一个解析结果，然后用http://xxx.xxx.xxx.xxx/eapi 的方式直接访问接口，这就会导致配置文件里面写的hosts无效。另外客户端现在会自动开启全局https，然后https转发没有证书会比较麻烦，需要信任个第三方证书，另外几个提供者也是这么做的。
其实解决方法也是有的，我个人自己在用Surge测试通过，首先是把所有的https请求干掉，这样App会自动回到http模式，至于用IP地址来访问请求的问题，直接用重定向定回music.163.com就行。
不过这个太麻烦，我还是建议直接使用Mac客户端下载音乐之后再导入到手机里。

**Comment by Aries0331** [comment]
好的感谢！
