### ISSUE TITLE
win10手动添加host，保存后自动添加了windows10.microdone.cn的host

### ISSUE THREAD

**Issue by oilbottle** [fengjueming/unblock-NetEaseMusic#31]
如图，这是啥问题啊，去都去不掉，只要保存又会自动添加上去

![image](https://user-images.githubusercontent.com/19664570/55535198-4e7fd280-566b-11e9-82d4-081ce6e89cf7.png)

**Comment by shenzj1994** [comment]
我猜是”微通新成“企业管理软件自动加的……和这个项目本身没关系……
你可以直接打开[http://www.microdone.cn/](http://www.microdone.cn/)看看。
