### ISSUE TITLE
Mac版本失效?

### ISSUE THREAD

**Issue by w-hc** [fengjueming/unblock-NetEaseMusic#32]
网易云音乐版本 Version 2.0.0 (730)
macOS version 10.14.4 (18E226)
新版的软件依然显示当前地区不支持播放

**Comment by xueyeshengdan** [comment]
确实失效了额

**Comment by hanglin3** [comment]
> 网易云音乐版本 Version 2.0.0 (730)
> macOS version 10.14.4 (18E226)
> 新版的软件依然显示当前地区不支持播放

我也是 之前可以用的 现在不行了
