### ISSUE TITLE
Arch Linux修改hosts文件后网易云音乐无法连接到网络

### ISSUE THREAD

**Issue by zhfans** [fengjueming/unblock-NetEaseMusic#34]
![Screenshot_20190511_121246](https://user-images.githubusercontent.com/50516716/57568328-1dbb5780-73e6-11e9-9385-3ae3af403f44.png)

**Comment by weirongxu** [comment]
我也一样，看起来是最新版默认使用 https API 了

**Comment by meinan99** [comment]
同问，求解决方法，我的删掉host以后还是无法连接网络

**Comment by ykangaf** [comment]
linux有客户端了马?

**Comment by 8ar10der** [comment]
> linux有客户端了马?

都快3年了吧……
