### ISSUE TITLE
服务器挂了么

### ISSUE THREAD

**Issue by Jackmatim** [fengjueming/unblock-NetEaseMusic#36]
服务器挂了么。连接不上了

**Comment by MelonRock** [comment]
我也是连接不上了。。求告知

**Comment by alvarso-mike** [comment]
同问，已经有一两天了。

**Comment by Tsingularity** [comment]
浏览器输music.163.com有惊喜lol

**Comment by 8ar10der** [comment]
> music.163.com

LOL, surprise CAT!

**Comment by fengjueming** [comment]
_(:3」∠)_重新弄了系统，准备试一下直接转发回国内服务器上，大概下周五之前咕好

**Comment by amaothree** [comment]
> _(:3」∠)_重新弄了系统，准备试一下直接转发回国内服务器上，大概下周五之前咕好

请问您是用了https://github.com/nondanee/UnblockNeteaseMusic这个项目搭建的服务器吗？我有cloudcone美西的服务器，不知道可不可以绕过地域限制（还是说只有日本服务器才行

**Comment by fengjueming** [comment]
> > _(:3」∠)_重新弄了系统，准备试一下直接转发回国内服务器上，大概下周五之前咕好
> 
> 请问您是用了 https://github.com/nondanee/UnblockNeteaseMusic 这个项目搭建的服务器吗？我有cloudcone美西的服务器，不知道可不可以绕过地域限制（还是说只有日本服务器才行

原理和他差不多，不过后来网易云加强了验证之后就比较麻烦了。我现在准备试一下弄个SS，限制白名单流量，然后直接接国内服务器，这样就没有SSL证书问题了。
