### ISSUE TITLE
有shadowrocket教程吗？ 我导入了CloudMusic.conf但是还是没用，请问一下如果解决？

### ISSUE THREAD

**Issue by zhiyicai** [fengjueming/unblock-NetEaseMusic#5]
有shadowrocket教程吗？ 我导入了CloudMusic.conf但是还是没用，请问一下如何解决？

**Comment by wangyiz4262** [comment]
@zhiyicai  貌似代理已经失效了

**Comment by fengjueming** [comment]
代理没失效，现在主要问题是网易云音乐的iOS客户端的处理方式变得特别复杂了。等我有空之后我再处理一下这个问题，现在Mac客户端没问题，建议优先使用Mac客户端下载

**Comment by wangyiz4262** [comment]
@fengjueming 修改Mac客户端是指修改hosts吗？还是在网易云音乐的客户端设置里面添加PAC文件地址到Proxy？谢谢！

**Comment by fengjueming** [comment]
直接修改hosts，我这边Mac客户端没啥问题，iOS的话我得找个时间抓包看看怎么处理……

**Comment by YahangWu** [comment]
看到ios客户端变得极为复杂，瞬间觉得很绝望。。。

**Comment by YahangWu** [comment]
win客户端的还host修改了 ip.ws.126.net 
以及把 music.httpdns.c.163.com 屏蔽为了本地

**Comment by fengjueming** [comment]
现在的解决办法只能伪全局代理，但是需要改动较大，我等有空了试一下看看能不能实现。
