### ISSUE TITLE
Mac 2.3.0版网络错误

### ISSUE THREAD

**Issue by juntingzh** [fengjueming/unblock-NetEaseMusic#50]
Mac客户端2.3.0版(Build 814)之前一直能用，前两天开始不行了。
打开网页music.163.com显示403 Forbidden

**Comment by tubalu** [comment]
早就放弃了.

**Comment by haowu-uiuc** [comment]
probably the proxy has been blocked

**Comment by juntingzh** [comment]
It works again now. Closing the issue.
