### ISSUE TITLE
所有图片无法加载？

### ISSUE THREAD

**Issue by Sinspiren** [fengjueming/unblock-NetEaseMusic#7]
解锁很好用，谢谢

但是有个问题，其他大部分https代理也这样不知道为什么，听歌，主页，专辑的图片都刷不出来，网上其他国家的朋友也这样

**Comment by fengjueming** [comment]
请问您用的是什么客户端？我这边Mac没有问题。

**Comment by yumehatoi** [comment]
Win7客户端就会出现这样的情况

**Comment by reilee** [comment]
貌似是因为网易云的多数图片服务器与音乐服务器不在同一个域名上
不过我这里没有问题，图片可以正常加载

**Comment by linghutiantian** [comment]
我这的Mac也是好用的。客户端和网页都没有问题。你的hosts文件有把 "music.163.com p1.music.126.net p2.music.126.net p3.music.126.net p4.music.126.net" 这些都加上了么？

**Comment by Nehalem-Lf** [comment]
我也是这样，win10 ，坐标台湾，私人FM也是一直loading
更正，把p1.music.126.net p2.music.126.net p3.music.126.net p4.music.126.net去掉就正常了，后面的是图片服务器？

**Comment by huj156** [comment]
今天突然就不要用了, 昨天还能用. 不知为什么?

**Comment by huj156** [comment]
今天突然就不能用了, 昨天还好使, 不知原因.

**Comment by fengjueming** [comment]
Sor，昨晚改完服务器配置忘了启动了。。。

**Comment by miriaford** [comment]
我这边也是，必须把 “p1.music.126.net p2.music.126.net p3.music.126.net p4.music.126.net” 删掉才行，否则任何音乐都听不了

**Comment by huj156** [comment]
是否能类似的解锁QQ音乐呢?

**Comment by fengjueming** [comment]
我不用QQ音乐，所以没有适配

**Comment by shugo-chara** [comment]
Android添加hosts归属地以及反代域名后还是不行，提示仅限国内

**Comment by shugo-chara** [comment]
Android添加hosts归属地以及反代域名后还是不行，提示仅限国内。封面的话现在不需要添加也可以正常显示
 @fengjueming

**Comment by fengjueming** [comment]
手机端现在太麻烦，不用SS或者VPN啥的很难实现。
