### ISSUE TITLE
shadowrocket 如何添加规则解锁网易云音乐

### ISSUE THREAD

**Issue by hwanginpen** [fengjueming/unblock-NetEaseMusic#9]
你好，

我有一个国内的节点，同时iphone上shadowrocket有一个配置文件，我只想开着配置模式然后访问网易云的时候走节点，访问外网直连，但是不清楚规则应该填写什么使其手机上用网易云的时候强制它走节点。
请问下我需要添加哪些规则呢？

谢谢！

**Comment by fengjueming** [comment]
USER-AGENT,NeteaseMusic*,Proxy
